name: l4
services:
  balancer:
    build:
      context: ./balancer
    container_name: balancer
    privileged: true # Required for RAW sockets
    volumes:
      - ./balancer/config_docker.yaml:/root/config.yaml
    ports:
      - "2050:2050/udp"
      - "8443:8443"
    networks:
      - l4_net

  server1:
    build:
      context: ./scripts/server
    container_name: server1
    command: ["2054"]
    networks:
      - l4_net

  server2:
    build:
      context: ./scripts/server
    container_name: server2
    command: ["2054"]
    networks:
      - l4_net

  server3:
    build:
      context: ./scripts/server
    container_name: server3
    command: ["2054"]
    networks:
      - l4_net

networks:
  l4_net:
    driver: bridge
