status_port: 8443
servers:
  - port: 2050
    broadcaster:
      - backend:
          addr: 'server1:2054'
          preserve_src_addr: true
          fake_src_ipv4_addr: '95.108.254.95'
          uuid: 'backend-1'
          weight: 1.0
      - backend:
          addr: 'server2:2054'
          preserve_src_addr: true
          fake_src_ipv4_addr: '95.108.254.95'
          uuid: 'backend-2'
          weight: 1.0
      - backend:
          addr: 'server3:2054'
          preserve_src_addr: true
          fake_src_ipv4_addr: '95.108.254.95'
          uuid: 'backend-3'
          weight: 1.0
