status_port: 8443
servers:
  - port: 2050
    duplicator:
      - backend:
          addr: '127.0.0.1:2054'
          preserve_src_addr: true
          fake_src_ipv4_addr: '95.108.254.95'
      - backend:
          addr: '127.0.0.1:2055'
          preserve_src_addr: true
          fake_src_ipv4_addr: '95.108.254.95'
      - backend:
          addr: '127.0.0.1:2056'
          preserve_src_addr: true
          fake_src_ipv4_addr: '95.108.254.95'
